# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "nightly"
profile = "default"
# https://rust-lang.github.io/rustup/concepts/components.html
components = [ "rust-src" ]
